# Generated by Django 5.0.1 on 2024-04-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Id')),
                ('fname', models.CharField(max_length=70, verbose_name='First Name')),
                ('lname', models.CharField(max_length=70, verbose_name='Last Name')),
                ('roll', models.IntegerField(unique=True, verbose_name='Roll')),
                ('mobile', models.CharField(max_length=12, verbose_name='Mobile')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Id')),
            ],
        ),
    ]
